# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZZYTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZZYTest
  pod 'Kingfisher'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxFlow'
  pod 'SnapKit'
  pod 'GeSwift'
  pod 'WrapNavgiationController'


  pod 'MGSwipeTableCell'
end
